robot_cfg:
  kinematics:
    urdf_path: "/home/hq/ros2_ws/src/frcobot_ros2-main/fairino_description/urdf/FR5WM.urdf"
    asset_root_path: "/home/hq/ros2_ws/src/frcobot_ros2-main"
    base_link: "base_link"
    ee_link: "wrist3_Link"
    
    collision_link_names: ['shoulder_Link', 'upperarm_Link', 'forearm_Link', 'wrist1_Link', 'wrist2_Link', 'wrist3_Link']
    collision_sphere_buffer: 0.0
    extra_collision_spheres: {}
    collision_spheres:
      shoulder_Link:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.05
      upperarm_Link:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.05
      forearm_Link:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.05
      wrist1_Link:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.05
      wrist2_Link:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.05
      wrist3_Link:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.05
          
    self_collision_ignore: {
      "shoulder_Link": ["upperarm_Link", "wrist3_Link"],
      "upperarm_Link": ["forearm_Link", "shoulder_Link", "wrist3_Link"],
      "forearm_Link": ["wrist1_Link", "wrist2_Link", "wrist3_Link"],
      "wrist1_Link": ["wrist2_Link","wrist3_Link"],
      "wrist2_Link": ["wrist3_Link"],
    }
    self_collision_buffer: {
      'upperarm_Link': 0, 
      'forearm_Link': 0, 
      'wrist1_Link': 0, 
      'wrist2_Link': 0,
      'wrist3_Link': 0
    }

    use_global_cumul: True
    mesh_link_names: ['shoulder_Link', 'upperarm_Link', 'forearm_Link', 'wrist1_Link', 'wrist2_Link', 'wrist3_Link']

    cspace:
      joint_names: ['j1', 'j2', 'j3', 'j4', 'j5', 'j6']
      retract_config: [0.0, -1.57, 1.57, -1.57, -1.57, 0.0]
      null_space_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      cspace_distance_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      max_jerk: 500.0
      max_acceleration: 12.0
      position_limit_clip: 0.1
